---
name: "New Task / Issue"
description: "Create a new issue with objective, description, tasks, and due date"
title: "New Task / Issue"
labels: []
assignees: []
---

Title: Enter a short title for this issue.

Objective: Describe the main goal or purpose of this task/issue.

Description: Provide details about what needs to be done.
- Include relevant notes, context, or constraints.
- Mention dependencies or related modules if needed.

To Do:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Due Date: Specify the target completion date.
