name: "📝 New Task / Issue"
description: "Create a new issue with objective, description, tasks, and due date"
title: "New Task / Issue"
labels: []

body:
  - type: input
    id: title
    attributes:
      label: "Title"
      description: "Enter a short title for this issue"
      placeholder: "Short summary of the task"
      required: true

  - type: textarea
    id: objective
    attributes:
      label: "Objective"
      description: "Describe the main goal or purpose of this task"
      placeholder: "Objective"
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide details about what needs to be done"
      placeholder: "Details, notes, dependencies"

  - type: checkboxes
    id: todo
    attributes:
      label: "To Do"
      description: "Tasks that need to be completed"
      options:
        - "Task 1"
        - "Task 2"
        - "Task 3"

  - type: input
    id: due_date
    attributes:
      label: "Due Date"
      description: "Specify the target completion date"
      placeholder: "YYYY-MM-DD"
